version: "3.9"

services:
  task_list_app:
    build: ../com.animalshelter
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_service:3306/db_animalshelter
      DB_USER_NAME: root
      DB_PASSWORD:
    restart: always
    depends_on:
      mysql_service:
        condition: service_healthy
  mysql_service:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: db_animalshelter
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10